//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTEColones
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraPromocion
    {
        public int IdBitacoraPromocion { get; set; }
        public string Operacion { get; set; }
        public string Usuario { get; set; }
        public string PromocionModificada { get; set; }
        public string DatoViejo { get; set; }
        public string ColumnaModificada { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Tabla { get; set; }
    }
}
