//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTEColones
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncargadoCentroAcopio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncargadoCentroAcopio()
        {
            this.CambioMaterialEstudiantes = new HashSet<CambioMaterialEstudiante>();
        }
    
        public int IdEncargadoCentroAcopio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CambioMaterialEstudiante> CambioMaterialEstudiantes { get; set; }
        public virtual CentroAcopio CentroAcopio { get; set; }
        public virtual InformacionBasica InformacionBasica { get; set; }
    }
}
