//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTEColones
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacionBasicaContacto
    {
        public int IdContacto { get; set; }
        public string Contacto { get; set; }
    
        public virtual InformacionBasica InformacionBasica { get; set; }
        public virtual TipoContacto TipoContacto { get; set; }
    }
}
