//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTEColones
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoMaterial()
        {
            this.CambioMaterialEstudiantes = new HashSet<CambioMaterialEstudiante>();
        }
    
        public int IdTipoMaterial { get; set; }
        public string NombreTipoMaterial { get; set; }
        public string CaracteristicaMaterial { get; set; }
        public double PesoBaseMaterial { get; set; }
        public double EquivalenciaTecolones { get; set; }
        public bool EstadoMaterial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CambioMaterialEstudiante> CambioMaterialEstudiantes { get; set; }
    }
}
